name: TEST1

on: 
 push:
   branches: 
     - main



jobs:
  Terraform_install_and_apply:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform init # Switch directory
      # working-directory: terraform_files/managed_groups
      run: terraform init
    
    # - name: Switch directory
    #   run: cd terraform_files/managed_groups

    - name: Terraform Plan
      # if: [ -f terraform_files/managed_groups/main.tf]; then
      run: cd terraform_files/managed_groups && terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve

    
    
   
 
