name: sample action

on:
 workflow_dispatch:
  inputs:
    description: 'type anything'
    required: false
    default: 'yaz1'
    type: Choise
    options: 
     - yaz1
     - yaz2

jobs:
  job1:
   runs-on: ubuntu-latest
   environment: host_name
   steps:
    - name: provide information from options
      uses: actions/checkout@v3.1.0
      output: ${{github.input}}
